routes/admin.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('logout' , 'Auth\LoginController@userLogout')->name('admin-logout');

  Route::group(['namespace'=>'Admin','middleware'=>'auth:admin','name'=>'dashboard.'],function (){
      Route::group(['prefix'=>'dashboard'],function (){
          Route::get('/','DashboardController@index')->name('admin.dashboard');
          Route::resource('governorates','GovernorateController')->except(['show']);
          Route::resource('cities','CityController')->except(['show']);
          Route::resource('blood-types','BloodTypeController')->except(['show']);
          Route::resource('category','CategoryController')->except(['show']);
          Route::resource('setting','SettingController')->except(['show','create','story','destroy']);
          Route::resource('reports','ContactController')->except(['show','create','story','edit','update']);
          Route::resource('post','PostController')->except(['show']);
          Route::resource('donation','DonationController')->except(['create'.'edit','story'.'update']);
          Route::resource('users','UserController')->except(['show']);
          Route::resource('clients','ClientController')->except(['show','edit','update','create','store']);
          Route::get('clients/{id}/status','ClientController@changeStatus')->name('clients.status');
          Route::get('changePassword','ChangePassController@change')->name('admin.change');
          Route::post('changePassword','ChangePassController@updateChange')->name('admin.update.change');

      });
  });


    Route::group(['namespace'=>'Admin','middleware'=>'guest:admin'],function (){
        Route::get('login','LoginController@getLogin')->name('get.admin.login');
        Route::post('login','LoginController@Login')->name('admin.login');

    });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('logout' , 'Auth\LoginController@clientLogout')->name('client-logout');

Route::group(['namespace'=>'Front','middleware'=>'auth:web'],function () {
    Route::get('Posts', 'MainController@posts')->name('posts');
    Route::get('details-Posts/{id}', 'MainController@postDetails')->name('details-posts');
    Route::post('toggle-favourite' , 'MainController@toggleFavourite')->name('toggle-favourite');
    Route::get('contact' , 'MainController@getContact')->name('contact.me');
    Route::post('contact' , 'MainController@contact')->name('push.contact');
    Route::get('postsFavorites' , 'MainController@getPostFavorites')->name('get.post.fav');
    Route::get('profile' , 'MainController@getProfile')->name('get.client.profile');
    Route::post('editProfile' , 'MainController@editProfile')->name('edit.client.profile');
    Route::get('donation' , 'MainController@donation')->name('client.donation');
});
Route::group(['namespace'=>'Front'],function (){
    Route::get('logins','LoginController@getClientLogin')->name('get.front.login');
    Route::post('logins','LoginController@Login')->name('front.login');
    Route::get('registers','RegisterController@getClientRegister')->name('get.front.register');
    Route::post('registers','RegisterController@Register')->name('front.register');
    Route::get('/home', 'MainController@home')->name('client-home');
    Route::get('about-us', 'MainController@about')->name('about.us');


});




Auth::routes();

app/Models/City.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{

    protected $table = 'cities';
    public $timestamps = true;
    protected $fillable = array('governorate_id','name');

    public function governorate()
    {
        return $this->belongsTo('App\Models\Governorate');
    }

    public function clients()
    {
        return $this->hasMany('App\Models\Client');
    }

    public function donationRequestes()
    {
        return $this->hasMany('App\Models\DonationRequest');
    }
    public function clientss()
    {
        return $this->belongsToMany('App\Models\Client');
    }

}

app/Http/Controllers/Admin/CityController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CityRequest;
use App\Models\City;
use App\Models\Governorate;
use Illuminate\Http\Request;

class CityController extends Controller
{

    public function index(Request $request)
    {
      $cities= City::where(function ($q) use ($request) {
          if($request->input('search')){
              return $q ->where('name','like','%'.$request->search.'%');
          }
          if($request->input('governorate_id')){
              return $q ->where('governorate_id',$request->governorate_id);
          }
      })->latest()->paginate("3");
      $governorates=Governorate::select('name','id')->get();
      return view('admin.city.index',compact('cities','governorates'));
    }

    public function create()
    {
        $governorates=Governorate::select('name','id')->get();
      return view('admin.city.create',compact('governorates'));
    }




    public function store(CityRequest $request)
    {
          $cities=City::create($request->all());
          return redirect()->route('cities.index')->with(['success'=>"تم الاضافه بنجاح"]);
    }


    public function edit($id)
    {
        $governorates=Governorate::select('name','id')->get();
        $cities=City::select('name','id')->find($id);
        if (!$cities){
            return  redirect()->route('cities.index')->with(['error'=>"هذه المحافظه ليست موجوده او ربما قام احد بحذفها"]);
        }
          return view('admin.city.edit',compact('cities','governorates'));
    }

    public function update(CityRequest $request, $id)
    {
        $cities=City::select('name','id')->find($id);
        if (!$cities){
            return  redirect()->route('cities.index')->with(['error'=>"هذه المحافظه ليست موجوده او ربما قام احد بحذفها"]);
        }
        $cities->update($request->all());
        return redirect()->route('cities.index')->with(['success'=>"تم النعديل بنجاح"]);
    }


    public function destroy($id)
    {
        $cities=City::where('id',$id)->find($id);
        if(!$cities){
            return  redirect()->route('cities.index')->with(['error'=>"هذه المحافظه لا يمكن حذفها لانها تقوم بحذف اشياء اخري"]);
        }
         $clients=$cities->clients();
        //بجيب التجار الي موجوده في القسم وبقوله لو فيه تجار ف القسم لايمكن حذفه
        if(isset($clients)&&$clients->count() >0) {
            return redirect()->route("cities.index")->with(['error' => 'لا يمكن حذف هذا القسم لان عند حذفه سيتم حذف اشياء اخري']);
        }

        $cities->delete();
        return redirect()->route('cities.index')->with(['success'=>'تم الحذف بنجاح']);
    }
}

resources/views/admin/city/create.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">  اضف محافظة </h6> <br>
                </div>
            </div>
            <div class="box-body">
                @include('admin.includes.alerts.errors')
                @include('admin.includes.alerts.success')
                <div class="card-body">
                <form action="{{route('cities.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>اسم المدينة </label>
                            <input class="form-control" type="text" name="name" value="{{old('name')}}">
                            @error("name")
                            <span class="text-danger">{{$message}} </span>
                            @enderror
                        </div>
                    </div>
                    <div class="col-md-12 " >
                        <div class="form-group">
                            <label for="governorate">اسم المحافظة </label>
                            <select name="governorate_id" class="select2 form-control" id="#governorate">
                                <optgroup label="من فضلك أختر المحافظه  ">
                                @if(isset($governorates)&&count($governorates))
                                    @foreach($governorates as $governorate)
                                <option value="{{$governorate->id}}">{{$governorate->name}}</option>
                                    @endforeach
                               @endif
                                </optgroup>
                            </select>
                            @error("name")
                            <span class="text-danger">{{$message}} </span>
                            @enderror
                        </div>
                    </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <button class="btn btn-primary btn-icon-split" type="submit" >
                                    <span class="icon text-white-50"><i class="fas fa-plus"></i>
                                    </span>
                                    <span class="text"> أضف مدينة</span>
                                </button>
                            </div>
                        </div>
                </form>
            </div>{{--end box body--}}
        </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/admin/city/edit.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">  اضف محافظة </h6> <br>
                </div>
            </div>
            <div class="box-body">
                @include('admin.includes.alerts.errors')
                @include('admin.includes.alerts.success')
                <div class="card-body">
                    <form action="{{route('cities.update',$cities->id)}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <input type="hidden" name="id" value="{{$cities->id}}"> {{-- عشان الصوره لو محبتش اغيرها --}}

                        <div class="col-md-12">
                            <div class="form-group">
                                <label>اسم المدينة </label>
                                <input class="form-control" type="text" name="name" value="{{$cities->name}}">
                                @error("name")
                                <span class="text-danger">{{$message}} </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-12 " >
                            <div class="form-group">
                                <label for="governorate">اسم المحافظة </label>
                                <select name="governorate_id" class="select2 form-control" id="#governorate">
                                    <optgroup label="من فضلك أختر المحافظه  ">
                                        @if(isset($governorates)&&count($governorates))
                                            @foreach($governorates as $governorate)
                                                <option value="{{$governorate->id}}" @if($governorate->id ==$cities->governorate_id)selected @endif>{{$governorate->name}}</option>
                                            @endforeach
                                        @endif
                                    </optgroup>
                                </select>
                                @error("name")
                                <span class="text-danger">{{$message}} </span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <button class="btn btn-primary btn-icon-split" type="submit" >
                                    <span class="icon text-white-50"><i class="fas fa-plus"></i>
                                    </span>
                                    <span class="text"> أضف مدينة</span>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>{{--end box body--}}
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/admin/city/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="container-fluid">

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">   المدن <small style="color:black;">{{$cities -> count()}}</small></h6>  <br>
                @include('admin.includes.alerts.errors')
                @include('admin.includes.alerts.success')
                <form action="" method="get">
                    @csrf
                    <div class="row">
                        <div class="col-md-4">
                            <input type="text" name="search" class="form-control" placeholder="search" value="" >

                        </div>
                        <div class="col-md-4">
                            <select class="form-control" name="governorate_id">
                                <optgroup label="من فضلك اختر المحافظه للبحث عنها"></optgroup>
                                <option class="hidden">-----</option>
                                @foreach($governorates as $governorate)

                                <option value="{{ $governorate->id}}">
                                    {{$governorate ->name}}
                                </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="col-md-4">
                            <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i> search</button>
                            @if(auth()->user()->haspermission('create_cities'))
                                <a class="btn btn-primary " href="{{route('cities.create')}}"><i class="fa fa-plus"></i> أضف</a>
                            @else
                                <a class="btn btn-primary disabled " href=""><i class="fa fa-plus"></i> أضف</a>
                            @endif

                        </div>

                    </div> {{-- end  row--}}

                </form> {{-- end form --}}

            </div>

            <div class="card-body">


                <div class="table-responsive">
                    @if(isset($cities)&&count($cities))
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>الاسم</th>
                            <th>المحافظه</th>
                            <th>التعديل</th>
                            <th>الحذف</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>

                            @foreach($cities as $index=> $city)

                            <td>{{$index +1 }}</td>
                            <td>{{$city ->name}}</td>
                            <td>{{$city ->governorate->name}}</td>
                            <td>
                                @if(auth()->user()->haspermission('update_cities'))
                                    <a href="{{route('cities.edit',$city->id)}}"   class="btn btn-primary btn-circle btn-lg"><i class="fas fa-info-circle"></i></a>
                                @else
                                    <a class="btn btn-primary btn-circle btn-lg disabled " href=""><i class="fas fa-info-circle"></i></a>
                                @endif
                            </td>

                                <td>
                                    @if(auth()->user()->haspermission('delete_cities'))
                                        <form action="{{route('cities.destroy',$city->id)}}" method="post" >
                                            {{csrf_field()}}
                                            {{method_field('delete')}}

                                            <button type="submit" class="btn btn-danger btn-circle btn-lg"> <i class="fas fa-trash"></i>
                                            </button>
                                        </form>
                                    @else
                                        <a class="btn btn-danger btn-circle btn-lg disabled " href=""><i class="fas fa-trash"></i> </a>
                                    @endif


                                </td>
                        </tr>


                        @endforeach

                        </tbody>
                    </table>
                    {{$cities->appends(request()->query())->links()}}
                    @else
                        <h2>data not found</h2>
                    @endif
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection