routes/admin.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('logout' , 'Auth\LoginController@userLogout')->name('admin-logout');

  Route::group(['namespace'=>'Admin','middleware'=>'auth:admin','name'=>'dashboard.'],function (){
      Route::group(['prefix'=>'dashboard'],function (){
          Route::get('/','DashboardController@index')->name('admin.dashboard');
          Route::resource('governorates','GovernorateController')->except(['show']);
          Route::resource('cities','CityController')->except(['show']);
          Route::resource('blood-types','BloodTypeController')->except(['show']);
          Route::resource('category','CategoryController')->except(['show']);
          Route::resource('setting','SettingController')->except(['show','create','story','destroy']);
          Route::resource('reports','ContactController')->except(['show','create','story','edit','update']);
          Route::resource('post','PostController')->except(['show']);
          Route::resource('donation','DonationController')->except(['create'.'edit','story'.'update']);
          Route::resource('users','UserController')->except(['show']);
          Route::resource('clients','ClientController')->except(['show','edit','update','create','store']);
          Route::get('clients/{id}/status','ClientController@changeStatus')->name('clients.status');
          Route::get('changePassword','ChangePassController@change')->name('admin.change');
          Route::post('changePassword','ChangePassController@updateChange')->name('admin.update.change');

      });
  });


    Route::group(['namespace'=>'Admin','middleware'=>'guest:admin'],function (){
        Route::get('login','LoginController@getLogin')->name('get.admin.login');
        Route::post('login','LoginController@Login')->name('admin.login');

    });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('logout' , 'Auth\LoginController@clientLogout')->name('client-logout');

Route::group(['namespace'=>'Front','middleware'=>'auth:web'],function () {
    Route::get('Posts', 'MainController@posts')->name('posts');
    Route::get('details-Posts/{id}', 'MainController@postDetails')->name('details-posts');
    Route::post('toggle-favourite' , 'MainController@toggleFavourite')->name('toggle-favourite');
    Route::get('contact' , 'MainController@getContact')->name('contact.me');
    Route::post('contact' , 'MainController@contact')->name('push.contact');
    Route::get('postsFavorites' , 'MainController@getPostFavorites')->name('get.post.fav');
    Route::get('profile' , 'MainController@getProfile')->name('get.client.profile');
    Route::post('editProfile' , 'MainController@editProfile')->name('edit.client.profile');
    Route::get('donation' , 'MainController@donation')->name('client.donation');
});
Route::group(['namespace'=>'Front'],function (){
    Route::get('logins','LoginController@getClientLogin')->name('get.front.login');
    Route::post('logins','LoginController@Login')->name('front.login');
    Route::get('registers','RegisterController@getClientRegister')->name('get.front.register');
    Route::post('registers','RegisterController@Register')->name('front.register');
    Route::get('/home', 'MainController@home')->name('client-home');
    Route::get('about-us', 'MainController@about')->name('about.us');


});




Auth::routes();

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

use Illuminate\Notifications\Notifiable;
use Tymon\JWTAuth\Contracts\JWTSubject;
use Illuminate\Foundation\Auth\User as Authenticatable;
class Client extends Authenticatable  implements JWTSubject
{
    use Notifiable;
    protected $table = 'clients';
    public $timestamps = true;
    protected $fillable = ['id','phone','status', 'password', 'email', 'name', 'dop', 'blood_type_id', 'last_donation_date', 'pin_code', 'city_id','governorate_id'];

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [];
    }

    public function bloodType()
    {
        return $this->belongsTo('App\Models\BloodType');
    }
    public function tokens()
    {
        return $this->hasMany('App\Models\Token');
    }

    public function city()
    {
        return $this->belongsTo('App\Models\City');
    }
    public function governorate()
    {
        return $this->belongsTo('App\Models\Governorate');
    }

    public function favorites(){
        return $this->belongsToMany('App\Models\Post');
    }

    public function donationRequestes()
    {
        return $this->hasMany('App\Models\DonationRequest');
    }

    public function notifications()
    {
        return $this->belongsToMany('App\Models\Notification');
    }

    public function bloodTypes()
    {
        return $this->belongsToMany('App\Models\BloodType');
    }

    public function governorates()
    {
        return $this->belongsToMany('App\Models\Governorate');
    }
    public function cities()
    {
        return $this->belongsToMany('App\Models\City');
    }
   public function getStatus(){
        return $this->status==1?'مفعل':'غير مفعل';
   }






}

app/Http/Controllers/Admin/ClientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\BloodType;
use App\Models\City;
use App\Models\Client;
use App\Models\Governorate;
use Illuminate\Http\Request;

class ClientController extends Controller
{

    public function index(Request $request)
    {
        $cities=City::select('id','name','governorate_id')->get();
        $bloodTypes=BloodType::select('id','name')->get();
        $governorates=Governorate::select('id','name')->get();
        $clients=Client::where(function ($qq) use($request){
            if($request->has('city_id')||$request->has('blood_type_id')||$request->has('governorate_id')||$request->has('search')){
                return $qq ->where('city_id',$request->city_id)->orwhere('blood_type_id',$request->blood_type_id)->orwhere('governorate_id',$request->governorate_id)->orwhere('name','like','%'.$request->search.'%');
            }
        })->latest()->paginate(4);
        return view('admin.clients.index',compact('clients','cities','bloodTypes','governorates'));
    }

    public function changeStatus($id){
        $clients=Client::FindOrFail($id);
        if(!$clients){
            return redirect()->route('clients.index')->with(['error' => 'هذا العميل غير موجود ربما قام احد بحذفه']);
        }
        if($clients->status==1){
            $clients->update([
                'status'=>0
            ]);
            return redirect()->route('clients.index')->with(['success'=>'تم الغاء التفعيل الحاله بنجاح']);
        }
        if($clients->status==0){
            $clients->update([
                'status'=>1
            ]);
            return redirect()->route('clients.index')->with(['success'=>'تم تفعيل الحاله بنجاح']);
        }
    }
    public function destroy($id)
    {
      $clients=Client::where('id',$id)->find($id);
      if(!$clients){
          return redirect()->route('clients.index')->with(['error'=>'حدذ حطأ ربما قام أحد بحذف هذا العميل']);
      }
      $clients->delete();
      return redirect()->route('clients.index')->with(['success'=>'تم الحذف بنجاح']);
    }


}

app/Http/Controllers/Api/Client/AuthController.php
<?php

namespace App\Http\Controllers\Api\Client;

use App\Http\Controllers\Controller;
use App\Mail\ResetPassword;
use App\Models\BloodType;
use App\Models\Client;
use App\Models\Token;
use App\Traits\General;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;


class AuthController extends Controller
{

    use General;

    public function register(Request $request){
        try {
            $validator=validator($request->all(),[
                'name'=>'required',
                'phone'=>'required|unique:clients,phone',
                'email'=>'required|unique:clients,email|email',
                'password'=>'required|confirmed',
                'governorate_id'=>'required|exists:governorates,id',
                'city_id'=>'required|exists:cities,id',
                'dop'=>'required',
                'last_donation_date'=>'required',
                'blood_type_id'=>'required'
            ]);
            if($validator ->fails()){
                return $this->responsesData('0','validation error',$validator->errors()->first(),'error');
            }

            $request_data=request()->except(['password']);
            $request_data['password']=Hash::make(request()->get('password'));
            $clients=Client::create($request_data);
            $blood_type=BloodType::where('id',$request->blood_type_id)->first();
            $clients->bloodTypes()->sync($blood_type);
            $clients->cities()->sync($request->city_id);
            $clients->governorates()->sync($request->governorate_id);
            return $this->responsesData('1','client',$clients,'تم الاضافه بنجاح');

        }catch (\Exception $ex){
            return $this->returnError($ex->getCode(), $ex->getMessage());
        }
    }

    public function login(Request $request){
        $validator=validator($request->all(),[
            'phone'=>'required',
            'password'=>'required'
        ]);
        if ($validator ->fails()){
            return $this->responsesData('0','validator error',$validator->errors(),'errors');
        }
        $credentials = $request->only(['phone','password']);

        $token = auth('clients-api')->attempt($credentials);
        if(!$token) {
            return $this->returnError('E003', 'بيانات الدخول غير صحيحة');
        }
        // return data and token
        $client= auth('clients-api')->user();
       $client-> api_token =$token;
        return $this -> responsesData('1' ,'client', $client);
    }
    public function rest_password(Request $request)
    {
        $validator=validator($request->all(),[
            'phone'=>'required',
        ]);
        if($validator->fails()){
            return $this->responsesData('0','validator error',$validator->errors(),'errors');
        }
        $client=Client::where('phone',$request->phone)->first();
        if($client){
            $code=rand('11111','88888');
            $update_code=$client->update(['pin_code'=>$code]);
            if($update_code){
                //send email message use mail trap or gmail
                Mail::to($client->email)
                    ->bcc('a7med.mostafa9900@gmail.com')
                    ->send(new ResetPassword($code));

                //send sms in mobile phone
                return $this->responsesData('success','pin_code_to_reset_password_is : ',$code,'انتظر رساله علي الفون بالكود');
            }else{
                return $this->returnError('E0003','حدث خطأ ما ولم يتم ارسال الكود ');
            }
        }else{
            return $this->returnError('E0003','لم يتم تسجيل ايميل بهذا الهاتف من قبل');
        }
    }
    public function forget_password(Request $request)
    {
        $validator = validator($request->all(), [
            'pin_code'=>'required',
            'password'=>'required|confirmed'
        ]);
        if ($validator->fails()) {
            return $this->responsesData('0', 'validator error', $validator->errors(), 'errors');
        }
        $client=Client::where('pin_code',$request ->pin_code)->where('pin_code','!=',0)->first();
        if($client){
            $client_new_pass=$client->update(['password'=>Hash::make(request()->get('password')),'pin_code'=>null]);
            return $this->responsesData('1','new_password',$client_new_pass,'تم اغير كلمه السر بمجاح');
        }else{
            return $this->returnError('E0003','هذا الكود غير صالح');
        }
    }
    public function register_token(Request $request){
        $validator=validator($request->all(),[
            'tokenFireBase'=>'required',
            'type'=>'required|in:android,ios',
        ]);
        if($validator->fails()){
            return $this->responsesData('0', 'validator error', $validator->errors(), 'errors');

        }
        Token::where('tokenFireBase',$request->tokenFireBase)->delete();
        $request->user('clients-api')->tokens()->create($request->all());
        return $this->returnSuccess('تم التسجيل بنجاح','500');
    }
    public function remove_token(Request $request){

    }

}

resources/views/admin/clients/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="container-fluid">

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">   العملاء <small style="color:black;">{{$clients -> count()}}</small></h6>  <br>
                @include('admin.includes.alerts.errors')
                @include('admin.includes.alerts.success')
                <form action="" method="get">
                    @csrf
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                <input type="text" name="search" class="form-control" placeholder="search" value="" >
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-4">
                                <label>اختر المدينه</label>
                                <select class="form-control" name="city_id">
                                    <optgroup label="من فضلك اختر المدينه للبحث عنها"></optgroup>
                                    <option class="hidden">-----</option>
                                    @foreach($cities as $city)

                                        <option value="{{ $city->id}}">
                                            {{$city->name}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="col-md-4">
                                <label>اختر المحافظه</label>
                                <select class="form-control" name="governorate_id">
                                    <optgroup label="من فضلك اختر المحافظه للبحث عنها"></optgroup>
                                    <option class="hidden">-----</option>
                                    @foreach($governorates as $governorate)

                                        <option value="{{ $governorate->id}}">
                                            {{$governorate->name}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-md-4">
                                <label> اختر الفصيله</label>
                                <select class="form-control" name="blood_type_id">
                                    <optgroup label="من فضلك اختر الفصيله للبحث عنها"></optgroup>
                                    <option class="hidden">-----</option>
                                    @foreach($bloodTypes as $bloodType)

                                        <option value="{{ $bloodType->id}}">
                                            {{$bloodType->name}}
                                        </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4">
                            <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i> search</button>
                        </div>
                    </div>
                </form> {{-- end form --}}

            </div>

            <div class="card-body">


                <div class="table-responsive">
                    @if(isset($clients)&&count($clients))
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>الاسم </th>
                            <th>الاميل</th>
                            <th>فصيله الدم</th>
                            <th>تاريخ الميلاد</th>
                            <th>أخر تاريخ للتبرع</th>
                            <th>المحافظه</th>
                            <th>المدينة</th>
                            <th>رقم الهاتف</th>
                            <th>الحالة</th>
                            <th>اجراء الحالة</th>
                            <th>الحذف</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>

                            @foreach($clients as $index=> $client)

                            <td>{{$index +1 }}</td>
                            <td>{{$client ->name}}</td>
                            <td>{{$client ->email}}</td>
                            <td>{{$client ->bloodType->name}}</td>
                            <td>{{$client ->dop}}</td>
                            <td>{{$client ->last_donation_date}}</td>
                            <td>{{$client ->governorate->name}}</td>
                            <td>{{$client ->city->name}}</td>
                            <td>{{$client ->phone}}</td>
                            <td>{{$client ->getStatus()}}</td>
                            <td>
                                <a href="{{route('clients.status',$client->id)}}"
                                   class="btn btn-outline-warning btn-min-width box-shadow-3 mr-1 mb-1">@if($client->status==0) تفعيل @else  الغاء تفعيل @endif </a>                            </td>

                                <td>

                                    <form action="{{route('clients.destroy',$client->id)}}" method="post" >
                                        {{csrf_field()}}
                                        {{method_field('delete')}}

                                        <button type="submit" class="btn btn-outline-danger btn-circle btn-lg"> <i class="fas fa-trash"></i>
                                        </button>

                                    </form>
                                </td>
                        </tr>


                        @endforeach

                        </tbody>
                    </table>
                    {{$clients->appends(request()->query())->links()}}
                    @else
                        <h2>data not found</h2>
                    @endif
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection