routes/admin.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('logout' , 'Auth\LoginController@userLogout')->name('admin-logout');

  Route::group(['namespace'=>'Admin','middleware'=>'auth:admin','name'=>'dashboard.'],function (){
      Route::group(['prefix'=>'dashboard'],function (){
          Route::get('/','DashboardController@index')->name('admin.dashboard');
          Route::resource('governorates','GovernorateController')->except(['show']);
          Route::resource('cities','CityController')->except(['show']);
          Route::resource('blood-types','BloodTypeController')->except(['show']);
          Route::resource('category','CategoryController')->except(['show']);
          Route::resource('setting','SettingController')->except(['show','create','story','destroy']);
          Route::resource('reports','ContactController')->except(['show','create','story','edit','update']);
          Route::resource('post','PostController')->except(['show']);
          Route::resource('donation','DonationController')->except(['create'.'edit','story'.'update']);
          Route::resource('users','UserController')->except(['show']);
          Route::resource('clients','ClientController')->except(['show','edit','update','create','store']);
          Route::get('clients/{id}/status','ClientController@changeStatus')->name('clients.status');
          Route::get('changePassword','ChangePassController@change')->name('admin.change');
          Route::post('changePassword','ChangePassController@updateChange')->name('admin.update.change');

      });
  });


    Route::group(['namespace'=>'Admin','middleware'=>'guest:admin'],function (){
        Route::get('login','LoginController@getLogin')->name('get.admin.login');
        Route::post('login','LoginController@Login')->name('admin.login');

    });

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('logout' , 'Auth\LoginController@clientLogout')->name('client-logout');

Route::group(['namespace'=>'Front','middleware'=>'auth:web'],function () {
    Route::get('Posts', 'MainController@posts')->name('posts');
    Route::get('details-Posts/{id}', 'MainController@postDetails')->name('details-posts');
    Route::post('toggle-favourite' , 'MainController@toggleFavourite')->name('toggle-favourite');
    Route::get('contact' , 'MainController@getContact')->name('contact.me');
    Route::post('contact' , 'MainController@contact')->name('push.contact');
    Route::get('postsFavorites' , 'MainController@getPostFavorites')->name('get.post.fav');
    Route::get('profile' , 'MainController@getProfile')->name('get.client.profile');
    Route::post('editProfile' , 'MainController@editProfile')->name('edit.client.profile');
    Route::get('donation' , 'MainController@donation')->name('client.donation');
});
Route::group(['namespace'=>'Front'],function (){
    Route::get('logins','LoginController@getClientLogin')->name('get.front.login');
    Route::post('logins','LoginController@Login')->name('front.login');
    Route::get('registers','RegisterController@getClientRegister')->name('get.front.register');
    Route::post('registers','RegisterController@Register')->name('front.register');
    Route::get('/home', 'MainController@home')->name('client-home');
    Route::get('about-us', 'MainController@about')->name('about.us');


});




Auth::routes();

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model 
{

    protected $table = 'categories';
    public $timestamps = true;
    protected $fillable = array('name');

    public function posts()
    {
        return $this->hasMany('App\Models\Post');
    }

}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    public function index(Request $request)
    {
        $categories=Category::when($request->search ,function ($q) use($request){
            return $q->where('name','like','%'.$request ->search.'%');
        })->latest()->paginate(10);
        return view('admin.categories.index',compact('categories'));
    }

    public function create()
    {
       return view('admin.categories.create');
    }


    public function store(CategoryRequest $request)
    {
        $categories=Category::create($request->all());
        return redirect()->route('category.index')->with(['success'=>'تم الاضافه بنجاح']);
    }


    public function edit($id)
    {
        $categories=Category::select('name','id')->find($id);
        if(!$categories){
            return  redirect()->route('category.index')->with(['error'=>"هذه المحافظه ليست موجوده او ربما قام احد بحذفها"]);
        }
        return view('admin.categories.edit',compact('categories'));

    }


    public function update(Request $request, $id)
    {
        $categories=Category::select('name','id')->find($id);
        if(!$categories){
            return  redirect()->route('category.index')->with(['error'=>"هذه المحافظه ليست موجوده او ربما قام احد بحذفها"]);
        }
        $categories->update($request->all());
        return  redirect()->route('category.index')->with(['success'=>"تم التعديل بنجاح"]);

    }



    public function destroy($id)
    {
        $categories=Category::where('id',$id)->find($id);
        if(!$categories){
            return  redirect()->route('category.index')->with(['error'=>"هذه المحافظه ليست موجوده او ربما قام احد بحذفها"]);
        }
       $posts= $categories->posts();
        if($posts &&$posts->count()>0){
            return redirect()->route("category.index")->with(['error' => 'للا يمكن حذف هذا القسم لان عند حذفه سيتم حذف اشياء اخري']);
        }
        $categories->delete();
        return  redirect()->route('category.index')->with(['success'=>"تم الحذف بنجاح"]);
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">  اضف قسم </h6> <br>
                </div>
            </div>
            <div class="box-body">
                @include('admin.includes.alerts.errors')
                @include('admin.includes.alerts.success')
                <div class="card-body">
                <form action="{{route('category.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label>اسم القسم </label>
                        <input class="form-control" type="text" name="name" value="{{old('name')}}">
                        @error("name")
                        <span class="text-danger">{{$message}} </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <button class="btn btn-primary" type="submit" ><i class="fa fa-plus"> </i>أضف </button>
                    </div>
                </form>
            </div>{{--end box body--}}
        </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Begin Page Content -->
    <div class="container-fluid">

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">  تعديل قسم </h6> <br>
                </div>
            </div>
            <div class="box-body">
                @include('admin.includes.alerts.errors')
                @include('admin.includes.alerts.success')
                <div class="card-body">
                    <form action="{{route('category.update',$categories->id)}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <input type="hidden" name="id" value="{{$categories->id}}"> {{-- عشان الصوره لو محبتش اغيرها --}}
                        <div class="form-group">
                            <label>اسم القسم </label>
                            <input class="form-control" type="text" name="name" value="{{$categories->name}}">
                            @error("name")
                            <span class="text-danger">{{$message}} </span>
                            @enderror
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit" ><i class="fa fa-plus"> </i>أضف </button>
                        </div>
                    </form>
                </div>{{--end box body--}}
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="container-fluid">

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">   المحافظات <small style="color:black;">{{$categories -> count()}}</small></h6>  <br>
                @include('admin.includes.alerts.errors')
                @include('admin.includes.alerts.success')
                <form action="" method="get">
                    @csrf
                    <div class="row">
                        <div class="col-md-4">
                            <input type="text" name="search" class="form-control" placeholder="search" value="" >

                        </div>
                        <div class="col-md-4">
                            <button class="btn btn-primary" type="submit"><i class="fa fa-search"></i> search</button>
                            @if(auth()->user()->haspermission('create_categories'))
                                <a class="btn btn-primary " href="{{route('category.create')}}"><i class="fa fa-plus"></i> أضف</a>
                            @else
                                <a class="btn btn-primary disabled " href=""><i class="fa fa-plus"></i> أضف</a>
                            @endif


                        </div>

                    </div> {{-- end  row--}}
                </form> {{-- end form --}}

            </div>

            <div class="card-body">


                <div class="table-responsive">
                    @if(isset($categories)&&count($categories))
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>الاسم</th>
                            <th>التعديل</th>
                            <th>الحذف</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>

                            @foreach($categories as $index=> $category)

                            <td>{{$index +1 }}</td>
                            <td>{{$category ->name}}</td>
                            <td>
                                @if(auth()->user()->haspermission('update_categories'))
                                    <a href="{{route('category.edit',$category->id)}}"   class="btn btn-primary btn-circle btn-lg"><i class="fas fa-info-circle"></i></a>
                                @else
                                    <a href=""   class="btn btn-primary btn-circle btn-lg disabled"><i class="fas fa-info-circle"></i></a>
                                @endif
                            </td>

                                <td>
                                    @if(auth()->user()->haspermission('delete_categories'))
                                        <form action="{{route('category.destroy',$category->id)}}" method="post" >
                                            {{csrf_field()}}
                                            {{method_field('delete')}}

                                            <button type="submit" class="btn btn-danger btn-circle btn-lg"> <i class="fas fa-trash"></i>
                                            </button>
                                        </form>
                                    @else
                                        <a class="btn btn-danger btn-circle btn-lg disabled " href=""><i class="fas fa-trash"></i> </a>
                                    @endif


                                </td>
                        </tr>


                        @endforeach

                        </tbody>
                    </table>
                    {{$categories->appends(request()->query())->links()}}
                    @else
                        <h2>data not found</h2>
                    @endif
                </div>
            </div>
        </div>

    </div>
    <!-- /.container-fluid -->
@endsection